name: TeamGames
main: me.D0mess.TG.TeamGames
version: 1.1
author: D0mess
description: Fun Team Games
commands:
  teamgames:
    description: Main command.
  stats:
    description: Stats command.
  endstats:
    description: End-Stats command.  
